### ISSUE TITLE
Unable to put embedded report into edit mode

### ISSUE THREAD

**Issue by jeffabailey** [Microsoft/PowerBI-JavaScript#214]
I'm getting this error when setting viewMode: 1 while loading an embedded report. I am able to load the report with viewMode == 0.

![insufficient permissions error](https://user-images.githubusercontent.com/776901/27503183-dcd224c6-582e-11e7-9ad8-ba3b608b20b8.PNG)

Embed code:
```javascript
        var config = {
            type: 'report',
            accessToken: accessToken,
            embedUrl: embedUrl,
            id: reportId,
            viewMode: 1,
            settings: {
                filterPaneEnabled: true,
                navContentPaneEnabled: true
            }
        };

        var report = powerbi.embed(document.getElementById('reportContainer'), config);
```
I have all permissions assigned to the app registration and can see them present when decoding the jwt.

Content.Create 
Dashboard.Read.All 
Data.Alter_Any 
Dataset.Read.All 
Dataset.ReadWrite.All 
Group.Read 
Group.Read.All 
Metadata.View_Any 
Report.Read.All 
Report.ReadWrite.All

I don't know if this is a bug or if I'm missing something.

**Comment by noanu** [comment]
Hi @jeffabailey 
Please look at the wiki of this gitHub - there is a documentation of the embedConfiguration that includes also the 'permissions' property that you should define in order to be able to switch or load in edit mode.
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details
You can also find the live demo very helpful - it also shows you the javaScript code so it is very easy to use:
https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html

**Comment by jeffabailey** [comment]
Thanks, I'll give that a shot.
