### ISSUE TITLE
Issue with type definition consolidation in 2.3.2.

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/PowerBI-JavaScript#225]
With the 2.3.2 and the consolidation of all the type definition, it resulted in the following error.  I had to downgrade to 2.3.1 to get it to work.

Line:
`import * as pbi from 'powerbi-client';`

results in error:
`error TS7016: Could not find a declaration file for module 'powerbi-client'. '/Users/darewreck/gitRepo/pulse-client/node_modules/powerbi-client/dist/powerbi.js' implicitly has an 'any' type.`

Also can the type definition be put it @types vs. tied to the project??

**Comment by darewreck54** [comment]
Also the only way that i could figure out how to create the powerbi is

`      this.powerbi = new pbi.service.Service(pbi.factories.hpmFactory, pbi.factories.wpmpFactory, pbi.factories.routerFactory);
   `

Is there another way to grab the powerbi instance?

**Comment by ali-hamud** [comment]
Hi @darewreck54 
if you need examples of how to use powerbi-client in typescript you can use these github as a reference:
https://github.com/Microsoft/PowerBI-Angular

and here is a live example implemented in typescript:
http://azure-samples.github.io/powerbi-angular-client/#/scenario1

you can see the app code in browser developer tools.

**Comment by darewreck54** [comment]
@ali-hamud  

The problem is that i'm using react.  So I'm not able to bring in the powerbi-angular library which probably simplifies it.  I could only find a partial powerbi-react-client example, but it was half complete and used the global instance of the powerbi object.

**Comment by ali-hamud** [comment]
Hi @darewreck54

don't use powerbi-angular in your solution. use it as a reference. see how it's implemented.

**Comment by stewx** [comment]
@ali-hamud I have the same issue as @darewreck54 and switching to 2.3.1 makes the error message go away.

**Comment by ali-hamud** [comment]
Oh I see.
I will look into it on sunday.
maybe powerbi-client has changed to something else.

**Comment by stewx** [comment]
Now I see the error message "File 'myproject/node_modules/powerbi-client/dist/powerbi-client.d.ts' is not a module."

**Comment by thor-schueler** [comment]
I can confirm this issue after upgrade from 2.3.1 in an ng4 app. Upgrade to 2.3.2 yields the 

`Could not find a declaration file for module 'powerbi-client'`

error. Upgrade to 2.3.3 resolves that only to now error with 

`File '/node_modules/powerbi-client/dist/powerbi-client.d.ts' is not a module.`

This issue is easy to reproduce:

- create new ng project with ng new
-` npm install --save powerbi-client@2.3.1 `
- import powerbi-client into the app.component.ts: `import * as pbi from 'powerbi-client';`
- use a type such as `let x:pbi.Report = null;`
- ng serve => no problems

Now upgrade powerbi-client to 2.3.3:
- `npm install --save powerbi-client@2.3.3`
- ng serve =>`ERROR in .../src/app/app.module.ts (7,22): File '.../node_modules/powerbi-client/dist/powerbi-client.d.ts' is not a module.`

If I copy the individual d.ts files from 2.3.1 into the 2.3.3 dist and remove the powerbi-client.d.ts, it works again. So this consolidation to one d.ts file is apparently not working correctly. Can this be undone until this is figured out?

**Comment by thor-schueler** [comment]
I got some more insight on this issue.  The problem is one of naming. When the d.ts files where conflated into the powerbi-client.d.ts ambient module declarations where introduced. However, the 'main' ambient module in powerbi-client.d.ts is called 'powerbi' (ln 1006 of powerbi-client.d.ts). 

Prior to 2.3.2, you could simply do:

`import { Report, Dashboard, ... } from 'powerbi-client'`

or simply

`import * as pbi from 'powerbi-client'`

starting with 2.3.2 this will break as powerbi-client.d.ts does not contain an ambient with name 'powerbi-client'. Instead, you will need to import from 'powerbi' (since that is the main ambient module). Of course, this will not work because typescript does not know powerbi. So we will ALSO need to do a side-effects only import of 'powerbi-client'

So for 2.3.2 and 2.3.3 you will need to do:

```
import 'powerbi-client';
import { Report, Dashboard, ... } from 'powerbi';
```
or
```
import 'powerbi-client';
import * as pbi from 'powerbi';
```

This is, of course, not very elegant. The problem can be solved more elegantly by aligning the name of the ambient module declaration with the npm module name. So if in line 1006 of powerbi-client.d.ts we change from

`declare module "powerbi" {`

to

`declare module "powerbi-client" {`

then the simplified pre 2.3.2 syntax of

`import { Report, Dashboard, ... } from 'powerbi-client'`

or simply

`import * as pbi from 'powerbi-client'`

will work again.  We should of course do that simply from a backward compatibility perspective. This should be as simple as renaming powerbi.ts to powerbi-client.ts in src/...

Thoughts?

**Comment by ali-hamud** [comment]
Thanks @thor-schueler 
Hope 2.3.4 will fix the issue. please try.

**Comment by thor-schueler** [comment]
Yes, the changes in 2.3.4 resolve the issue. I closed the associated pull request. I think this issue as well as #176 can be closed. 

For reference, to see a concrete example how to use this library in typescript (specifically with ng2/ng4) see [https://infusion-code.github.io/powerbi-ng2/](https://infusion-code.github.io/powerbi-ng2/) which provides a number of ng components that wrap powerbi-client for easier use in angular. This should provide a great go by on how to interact with powerbi-client from a typescript perspective.

**Comment by ali-hamud** [comment]
Thanks @thor-schueler.
