### ISSUE TITLE
Problem with setFilter() with having to consolidate all values

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/PowerBI-JavaScript#253]
When calling setFilters(filters) multiple times, it seems that the function doesn't take into account what is already a filter.  

Example:
```
filter_a_1 {
  table: a
  column: b
  operator: "In"
  values: "a"
}

filter_a_2 {
  table: a
  column: b
  operator: "In"
  values: "b"
}

filter_a_3 {
  table: a
  column: b
  operator: "In"
  values: "a","b"
}

```
1) setFilters( [filters_a_1 ,filters_a_2] )
2) setFilters([filters_a_3])

Currently, 1 and 2 would produce different results.  I would expect them to give the same results.  To get the right answer, all the values for the same filters with the same table and column name need to be combined to work properly.

Was this the intended design?

Thanks,
Derek

**Comment by ali-hamud** [comment]
yes this is true.
if you want to append. call get filters first

**Comment by ali-hamud** [comment]
Oh sorry, I read it wrong.
1 and 2 should give you the same result.
I will check that on sunday.

**Comment by ali-hamud** [comment]
@darewreck54 
do you make the two calls one by one?
pay attention that setFitlers is an async call, so, if you make two calls, one may be overridden by the other.

if you want to make two calls, make sure the first one is done.
setFilters(..).then(filters => setFilters( ....

**Comment by darewreck54** [comment]
@ali-hamud Let me double check on that.  I thought i did all the calls async.

But why do the setFilters need to be chained if I don't care about the results.  Ideally, I imagine that you can send multiple async setFilters call and it shouldn't drop one call over the next.

In the example above, why would the two calls override each other.  They are adding the addition of a value that is different to the same filter.  I would understand that if two calls were made and they change the same value of a filter, but this is just the addition of two different values of a filter.  I imagine, that there is some locking mechanism that applies one change and then the next.  If values are different, no override should happen.  

Also how would this work with two clients that access the same report.  Each each report rendering different based on some unique ID generated by each client connection when you trigger .embed?

**Comment by ali-hamud** [comment]
Each iframe has different state. setting filters on one embedded report instance will not affect the other instance. so, your users are ok.
setFilters is Async function, settings filters can take long time to complete, specially when you remove filters by setFilters([]).
when you call setFilters, power bi validates that the input is ok, if yes, setFilters starts a thread which applies the filters and return a resolved promise.
setFilters override the current list of filters with the list you provide.

Anyway, I read the first post again, the problem you described in first post should not appear. that means, the following are the same:
setFilters( [filters_a_1 ,filters_a_2] )
setFilters([filters_a_3])

as I said before, this maybe occurred due to other bug which has been resolved. please re-check and let me know if the problem still there.

**Comment by darewreck54** [comment]
HI Ali, 

Okay, that kind of clarifies it.  I thought using the IN operator treated it as an AND always.  Didn't distinguish the difference between how the filters are being used and how applying it the second method implies an OR operator.  

So whenever i get the filters, I need to also example the operator to determine the way the filter is being used.   That part wasn't that intuitive at first until you mentioned it. 

Thanks,
Derek

**Comment by ali-hamud** [comment]
what you want is:
filter_a_3 {
  table: a
  column: b
  operator: "In"
  values: "a","b"
}

"All" means all values, and it will give the same results as not passing the filter, but the filter card will be shown on filters pane.
usage:
filter_a_3 {
  table: a
  column: b
  operator: "All"
}
