### ISSUE TITLE
Phased loading not working for filters

### ISSUE THREAD

**Issue by mortenf** [Microsoft/PowerBI-JavaScript#314]
With the standard `embed` call (using API v2.3.1), embedding works, but suffers from drive-by-filtering: When data first shows up, it is without filters applied. After about a second or less, the data is filtered correctly according to the configured filters:

```
var report = powerbi.embed($('#reportContainer')[0],
	{
		type: 'report',
		tokenType: models.TokenType.Embed,
		accessToken: "...",
		embedUrl: "...",
		id: "...",
		permissions: models.Permissions.All,
		filters: [
			{$schema: "http://powerbi.com/product/schema#basic", target: { table: "Environment", column: "ShortName" }, operator: "In", values: ["dev"]},
			{$schema: "http://powerbi.com/product/schema#basic", target: { table: "Customer", column: "Key" }, operator: "In", values: [11,88]}
		],
		settings: {
			filterPaneEnabled: false,
			navContentPaneEnabled: false,
		}
	});
```

With the new phased loading feature (v2.4.6), we hoped this could be solved, however it doesn't seem to work as advertised.

```
var config = {
		type: 'report',
		tokenType: models.TokenType.Embed,
		accessToken: "...",
		embedUrl: "...",
		id: "...",
		permissions: models.Permissions.All,
		settings: {
			filterPaneEnabled: false,
			navContentPaneEnabled: false,
		},
		filters: [
			{$schema: "http://powerbi.com/product/schema#basic", target: { table: "Environment", column: "ShortName" }, operator: "In", values: ["dev"]},
			{$schema: "http://powerbi.com/product/schema#basic", target: { table: "Customer", column: "Key" }, operator: "In", values: [11,88]}
		]
	};
var report = powerbi.load($('#reportContainer')[0], config);
report.on('loaded', () => {
	console.log('Report loaded');
	report.render();
});
report.on('rendered', () => {
	console.log('Report rendered');
});
```

The above code, based on the example provided in the documentation, results only in a single `loaded` event, and then a 401 for `https://wabi-north-europe-redirect.analysis.windows.net/powerbi/metadata/models`.

If the `report.render();` call is changed to `report.render(config);` the embedding "works" again - the result is two `loaded` events and one `rendered` event, and the visuals in the report start showing up like before, with filters still being applied after the initial load/render.

If this is the intended behaviour, please update the documentation to reflect this. Also, we then have to work around it by hiding the report container element and showing it after the `rendered` event.

**Comment by ali-hamud** [comment]
Hi @mortenf 

1) Failed request: https://wabi-north-europe-redirect.analysis.windows.net/powerbi/metadata/models should not affect the embed functionality, it's a know issue and the fix will be deployed soon to production. you can ignore it.

2) Report shows with cached data, and then a query data request issued to the service in order to get the filtered data. we have a task in our backlog to disable a cache when dynamic filters are passed. phased loading will not solve this issue for you.

3) a work around to this behavior is: hide the iframe and show it only after you get the "rendered" event.
This work around is not the best, because if you have multiple visuals, the report will show only after all the visuals are ready.

**Comment by ali-hamud** [comment]
OH, another thing.
If you don't want to show the cached data due to security perspective, then it's not the right way to do it. the right way is to use RLS because these filters are client side only, RLS is the solution.
Read about: using RLS with Power BI Embed Tokens.

Another thing, if you have RLS context in Embed Token, the filtered data will show. you can "use" to avoid having a cached data. just pass empty RLS context in Generate Token request and it will work for you.

**Comment by andresfelipeardila** [comment]
I'm having the same issue @mortenf . Any updates?

**Comment by andresfelipeardila** [comment]
Hi @ali-hamud ,

I'm having the same issue than @mortenf . We don't want to show the cached data first but it's because it doesn't look right that after one second or less the filters are applied. The initial report visualization should come with filters already applied.

**Comment by andresfelipeardila** [comment]
For how long the report is cached?

**Comment by ali-hamud** [comment]
@mortenf , @andresfelipeardila 
Fix will get to production in 4 weeks.
For now you can use one of the mitigation I mentioned before:
1) use the rendered event
2) use an empty RLS context in Embed Token.

Thank you for reporting this.

**Comment by mortenf** [comment]
Thanks.

We are currently using the hide-render-show work around - and yes, we realize it's not a secure solution.
