### ISSUE TITLE
Missing a “Refresh” method to efficiently refresh a report/tile

### ISSUE THREAD

**Issue by RuiRomano** [Microsoft/PowerBI-JavaScript#4]
Specially for the reports because today if I just want to refresh I need to recreate the Iframe and I believe it’s slower than sending a postmessage to the iframe with “loadReport”

Something like: window.powerbi.refresh(container)

**Comment by mattmazzola** [comment]
With the pull requested referenced above you can achieve a refresh by calling:
`powerbi.embed(container, { ... })` where container is an html element which already contains an embedded report. This essentially sends postMessage with action of 'loadReport'.

I'm will look into adding a refresh method although I'm a little hesitant because I want to make sure we don't increase the surface area of the api too much and end up having overlap which causes confusion and then breaking changes if we consolidate in the future.

That being said, I understand although calling embed works it isn't exactly the same use case and requires passing the same information back to the embed method which doesn't make sense since it's obvious it should re-use whatever the existing configuration is.

We can either add refresh directly on the service as you suggested or on the component instance.
I'm leaning a little more towards it being on the component instance because I it's more semantic.  You have an instance of report and simply refresh it by calling `report.refresh()`. The downside of it being on the component is that I think the way most people are writing code they won't have a saved reference to the component and will end having to call two methods as:

Let me know what you think, and I'll get some discussions started with @wbreza.

**Comment by mattmazzola** [comment]
Hmm, not sure what I messed up in the commit message. I thought this should have been auto-closed.

In summary, `report.reload()` should fill the need for this issue.  In the future, we might have `dashboard.reload()` and other embed types.

**Comment by pelocruz** [comment]
Hi,

We have a problem maybe related to this thread. We have a report that reads data from a database using DirectQuery. We have embedded the report in a website using this Javascript API. We would like to update the report programatically, so that the query is run again and the data in the report is updated. We have tried using both report.reload and powerbi.embedExisting. The report visuals seem to update, but the data doesn't. Is there any functionality for updating/refreshing the dataset using the Javascript API? Are we doing something wrong?

Thanks

**Comment by mattmazzola** [comment]
This `reload()` method is for re- loading the report as if you called `report.load()` with the same configuration as before.  It's a convenience method that prevents you from having to keep that configuration object around in your code.

**Is there any functionality for updating/refreshing the dataset using the Javascript API?**
Yes, refresh data using the `report.refresh()` method seen here:
https://github.com/Microsoft/PowerBI-JavaScript/blob/dev/src/report.ts#L184

For information on data refresh limits see this:
https://powerbi.microsoft.com/en-us/documentation/powerbi-refresh-data/

Also, `powerbi.embedExisting` is a private method and should not be called by consumers.

**Comment by pelocruz** [comment]
Thank you very much for the explanation. Like you say, it doesn't seem like the `refresh()` method is responding to the call. We will wait until this is included in a release JavaScript API.
