### ISSUE TITLE
sequence of report.load and report.setfilter

### ISSUE THREAD

**Issue by mschulz531** [Microsoft/PowerBI-JavaScript#51]
I've got code written that calls report.load and then calls report.setfilter.  However, the specified filter is not being set...based on the log messages it appears that setFilter is being called before the report.load is completed...and perhaps that is why my filter is not being accepted?

Is there an event handler for report.loaded that I should use to set the filter?
or something else?

**Comment by mattmazzola** [comment]
**it appears that setFilter is being called before the report.load is completed**
Yes, this is likely what is happening.  The promise returned by `load` method only indicates the request was accepted, not that it's completed.  Almost all of our methods which change the state of the report are asynchronous style API with events.

** it appears that setFilter is being called before the report.load is completed**
Yes, there is a `loaded` event.  The demo applications and wiki have examples of setting up event handlers.

You always wait until the `loaded` event occurs before attempting to send other commands to the report or it likely won't be able to respond since the application is not finished initializing.
