### ISSUE TITLE
How to work with PowerBI Embedded?

### ISSUE THREAD

**Issue by rolandoldengarm** [Microsoft/PowerBI-JavaScript#53]
I've used the PowerBI CLI to upload a PBIX.
I've tried to follow this example to embed it, but nothing seems to happen.

https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embedding-Basics

What should I use for the powerbi-embed-url ?
I only have an access token (from the Azure Portal).
A step-by-step guide would be appreciated.

**Comment by mschulz531** [comment]
https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-get-started/

https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-get-started-sample/

**Comment by mattmazzola** [comment]
**What should I use for the powerbi-embed-url?**
`https://embedded.powerbi.com/appTokenReportEmbed`

**I only have an access token (from the Azure Portal).**
You use the access key to issue an embed token. The embed token is a JWT with specific claims for the report.  The access key from the azure portal is a secret. ***DO NOT use the the access key from azure portal in your client side code since this would be exposing it for others to use maliciously.***  If you have already accidentally done this it would be advised to regenerate your access keys to invalidate the previous keys.  You can do this using the Azure portal or the [azure-cli](https://www.npmjs.com/package/azure-cli) tool.

For information about issuing tokens you can use our node cli or csharp cli tools:
Node: https://github.com/Microsoft/PowerBI-Cli
CSharp: https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/tree/master/ProvisionSample

To look a sample REST service see:
https://github.com/Azure-Samples/powerbi-dotnet-server-aspnet-web-api

A step-by-step guide would be appreciated
Yes, we are continually working to improve the documentation.  Currently the [wiki](https://github.com/Microsoft/PowerBI-JavaScript/wiki) is most complete source of information.

**Comment by rolandoldengarm** [comment]
@mattmazzola sorry to bother you again, but it's still not obvious.
I'm using Webpack, so I'm importing it into a typescript module.

Then, I'm doing this:
````
import * as pbi from 'powerbi-client';
declare var powerbi;
this.domElement.innerHTML = `<div id="reportContainer"></div>`;
    var embedConfiguration = {
      type: 'report',
      accessToken: '<embed token>',
      id: '<report id>',,
      embedUrl: 'https://embedded.powerbi.com/appTokenReportEmbed'
  };
 var $reportContainer = $('#reportContainer');
  var report;
  fetch(embedConfiguration.embedUrl).then((response) => {
    if (response.ok) {
      return response.json()
        .then(function (embedConfig) {
          report = powerbi.embed($reportContainer.get(0), embedConfig);
        });
    }
  });
````
But, I get a CORS issue:
![image](https://cloud.githubusercontent.com/assets/14539000/18454796/8fed293a-799a-11e6-9823-4904e55d4672.png)

Other than that, I'm importing pbi, but that does not contain a method embed? So that's why I'm declaring powerbi as a global.

None of the samples are trying to use Embedded as far as I can tell.

Hopefully you can point me in the right direction!

**Comment by rolandoldengarm** [comment]
@mattmazzola I've "fixed" it now like this:

````
    let powerbi = new pbi.service.Service(pbi.factories.hpmFactory, pbi.factories.wpmpFactory, pbi.factories.routerFactory);
    report = powerbi.embed($reportContainer.get(0), embedConfiguration);
````

**Comment by mattmazzola** [comment]
This request `fetch(embedConfiguration.embedUrl)` is incorrect.  That is causing the CORS error.

The embedUrl is the src for the iframe.  The URL is different depending on type and authentication method.  Such as report vs dashboards and SaaS (AAD user token) embed vs PaaS (custom report token).

The `fetch` call in the samples uses API to demonstrate what you might implement on your own.
You need to issue your own tokens for your own reports using some secure service. CSharp, node, Python etc...

`import * as pbi from 'powerbi-client';`
Here `pbi` is reference to module, not an instance of the Service class.
The `powerbi` global is the service instance.

**Comment by rolandoldengarm** [comment]
> The powerbi global is the service instance.

But, when I do "declare var powerbi;" I get an undefined exception, that powerbi is not defined.

See my previous comment, I'm now instantiating the service manually, and that's working :+1: But I don't think that's the way to go...

**Comment by aurelienprevotMVP** [comment]
Hello,

I had the same problem developing with the SharePoint Framework & Power BI :  `import * as pbi from 'powerbi-client';` don't load the `powerbi` global service instance.
So, I needed to re-instanciate the service as Matt did ! (juste spending three hours on this... ;-)

**Comment by rolandoldengarm** [comment]
@aurelienprevotMVP Please see my example at the SharePoint github repo as well, maybe that helps: https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev/samples/js-powerbi-embedded

**Comment by aurelienprevotMVP** [comment]
@rolandoldengarm Thank ! I will check that ! I wanted to do exactly the same thing, but it seems you were there before me ! Do you need some help to improve this project ?

**Comment by rolandoldengarm** [comment]
@aurelienprevotMVP no, all good, thanks. Example shows the basics how to use PowerBI JS in SPFX.

**Comment by rneven** [comment]
@mattmazzola 

> The URL is different depending on type and authentication method. Such as report vs dashboards and SaaS (AAD user token) embed vs PaaS (custom report token).

--> Different how? We now use https://embedded.powerbi.com/appTokenReportEmbed?reportId=e1485a1a-cd... in our PHP-code (attached below this message) to generate the access/embed token and in our JavaScript to post this token into the iFrame. Would this be correct?

> You need to issue your own tokens for your own reports using some secure service. CSharp, node, Python etc...

--> Would it be possible to do this in JavaScript directly (so instead of the PHP-code we use now, as I mentioned above)?

Many thanks in advance!

[PHP code to create PBIE access token and posting it into iFrame - Anonymous.txt](https://github.com/Microsoft/PowerBI-JavaScript/files/673922/PHP.code.to.create.PBIE.access.token.and.posting.it.into.iFrame.-.Anonymous.txt)

**Comment by ali-hamud** [comment]
Hi,

**_First question_** 

**If you are embedding a reports from PowerBI.com:**
`embedUrl: 'https://app.powerbi.com/reportEmbed?reportId=...'`

If you are using our JavaScript library you should use
```
var embedConfiguration = {
    type: 'report',
    id: '5dac7a4a-4452-46b3-99f6-a25915e0fe55',
    embedUrl: 'https://app.powerbi.com/reportEmbed'
};
```

**If you are embedding a report from a workspace collection in azure:**
`embedUrl: 'https://embedded.powerbi.com/appTokenReportEmbed?reportId=...'
`
If you are using our JavaScript library you should use
```
var embedConfiguration = {
    type: 'report',
    accessToken: 'eyJ0eXAiO...Qron7qYpY9MI',
    id: '5dac7a4a-4452-46b3-99f6-a25915e0fe55',
    embedUrl: 'https://embedded.powerbi.com/appTokenReportEmbed'
};
```

**_for more info please look here:_**
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embedding-Basics

For your second question:
Would it be possible to do this in JavaScript directly (so instead of the PHP-code we use now, as I mentioned above)?
Answer is NO.
Javascript code is running in Frontend. to generate embed token, you need to use your workspace collection access keys. you should not save these access key in frontend code, otherwise users can do anything they want to your workspace collection.

if your server is a nodeJS server, you can use the powerbi-node library to generate access token:
https://github.com/Microsoft/PowerBI-Node

if your server is .NET, you can use our nugets:
nuget.org/profiles/powerbi

**Comment by rneven** [comment]
@ali-hamud 

Thank you very much for your reply, we are progressing slowly. We are currently, more or less successfully, embedding a .pbix report in our web application built in our front end development tooling Outsystems using the following piece of JavaScript (see below, we are using an Embed Token Web API for embedding). 
Somehow though, we cannot get the default page setting in the embedConfiguration variable to work. It keeps popping up the last report section (number 5 out of 5, i.e. ReportSection4) as default page. Can anyone spot anything incorrect in this code? Thank you very much in advance!

`<script>

 var embedConfiguration = {
 type: 'report',
 accessToken: '" + EncodeJavaScript(AppToken) + "',
 id: '" + EncodeJavaScript(ReportId) + "',
 embedUrl: '" + EncodeJavaScript(URL) + "',
 settings: {
 filterPaneEnabled: false,
 navContentPaneEnabled: false,
 pageName: 'ReportSection1'
 }
 };

 var reportContainer = document.getElementById('"+ PowerBIReport.RuntimeId +"_report');

 // Embed the report and display it within the div container.
 var report = powerbi.embed(reportContainer, embedConfiguration);

 // Report.off removes a given event handler if it exists.
 report.off('loaded');

 // Report.on will add an event handler which prints to Log window.
 report.on('loaded', function() {
 console.log('Report loaded');
 });


 </script> `

**Comment by ali-hamud** [comment]
pageName is not part of settings, it is part of embedConfiguration.

your embedConfiguration should be:

var embedConfiguration = {
type: 'report',
accessToken: '" + EncodeJavaScript(AppToken) + "',
id: '" + EncodeJavaScript(ReportId) + "',
embedUrl: '" + EncodeJavaScript(URL) + "',
settings: {
filterPaneEnabled: false,
navContentPaneEnabled: false
},
pageName: 'ReportSection1'
};

**Comment by rneven** [comment]
@ali-hamud Super, thank you so much, that solved it!

**Comment by rneven** [comment]
Another question in this area: what is your solution for finding out the report pages/sections numbers? Because once you delete and reshuffle pages, the section numbers do no line up anymore and it seems almost impossible to find out the correct section number for each page after that. 

 As this guy found out as well: 

https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/16700383-i-would-like-for-pages-to-update-to-reflect-their

Thank you!

**Comment by acomito** [comment]
I'm trying to follow this example, but it's saying my type is not defined:

https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html

**Comment by ali-hamud** [comment]
live sample is written in javascript and accessing powerbi which is defined on window object by powerbi.js.
seems like your application is written in typescript.
anyways, glad to hear it worked for you.
