### ISSUE TITLE
Support for IE8 and Promises?

### ISSUE THREAD

**Issue by mschulz531** [Microsoft/PowerBI-JavaScript#54]
The following code fails on 
	        `var promise = new Promise(function (resolve, reject) {`
in IE8: Promise not defined.

```
WindowPostMessageProxy.createDeferred = function () {
	        var deferred = {
	            resolve: null,
	            reject: null,
	            promise: null
	        };
	        var promise = new Promise(function (resolve, reject) {
	            deferred.resolve = resolve;
	            deferred.reject = reject;
	        });
	        deferred.promise = promise;
	        return deferred;
	    };
```

Is there a way to get support for Promise in IE8?
If so, what do I need to do?

I found this version of es6-promise which supposedly supports IE8, but I don't see where the powerbi-javascript source code includes it, unless it is "built-in".

https://github.com/stefanpenner/es6-promise

**Comment by mattmazzola** [comment]
Yes, we have dependency on that exact library.  It is the correct polyfill to use to simulate native Promise support in older browsers.

It is seen here:
https://github.com/Microsoft/window-post-message-proxy/blob/master/package.json#L32

This site should tell you which browsers need the polyfill (those in red):
http://caniuse.com/#search=Promise

However, `es6-proimse` is not bundled with the library because we didn't want to increase our library size with this extra code if it is not needed in the normal use case.  You can include it manually and it should solve the issue. 

**Is there a way to get support for Promise in IE8?**
Yes

**If so, what do I need to do?**
Adding a simple script tag might be easiest, otherwise using your own bundling with our libraries:
```
<script src="https://npmcdn.com/es6-promise@3.2.1"></script>
```

This does bring up the question of whether it can be moved from dependency to devDependency since we're not actually including the code.  That would probably be separate issue though.

**Comment by mschulz531** [comment]
Matt,
Thanks, including the script for npmcdn.com/es6-promise worked like a champ.
