### ISSUE TITLE
IEmbedConfiguration filters are not being applied during load - powerbi.embed()

### ISSUE THREAD

**Issue by jhorgan** [Microsoft/PowerBI-JavaScript#56]
When I use a filter as part of the initial configuration, passed to powerbi.embed(elm, configuration), it doesn't get applied. Should it or must I hook into the 'loaded event' and set the filter there?

**Comment by mschulz531** [comment]
Just dealt with this myself...there is a bug. You need to hook into the on.loaded event and set it thete, works like a charm.

**Comment by mattmazzola** [comment]
Yes, this bug is related to #50 There is error in schema validation happening.

There is more detail here:
https://github.com/Microsoft/powerbi-models/issues/16

A fix was already comitted to the SDK here:
https://github.com/Microsoft/PowerBI-JavaScript/commit/01f12161692075235836fb20f072945a60fd75bd

And the fix has be submitted to product code but will have to go through the longer product deployment pipeline which takes a few weeks.  Since there is a workaround with `setFilters` it wasn't able to be pushed to the fast track.

I'll keep this one open so people know there is bug instead of having to go to powerbi-models repo which might appear unreleated.

**Comment by ali-hamud** [comment]
Please try again. it should work not. I validated.
I am closing the issue, please re-open if it doesn't work for you.

**Comment by jmacweb** [comment]
HI Matt/Ali-

Has this been fixed?  I have the latest version of the sample download, and power bi, but still not able to add filters to the embed config.  This is a deal breaker for our scenario.

**Comment by ali-hamud** [comment]
Can you please give an example of the filter you are trying?
Does it contain a date?

**Comment by jmacweb** [comment]
Yes, I added it here: Issue with Filter: https://github.com/Microsoft/powerbi-models/issues/16
